DEBUG: false

HOST: localhost
PORT: 8908

MONGO_URI: <MONNGO URI HERE>

MONGO_VECTORSTORE_COLLECTION_NAME: dummy_test_store
MONGO_VECTORSTORE_DB_NAME: vectorstores
MONGO_FILES_METADATA_COLLECTION_NAME: files_metadata

COHERE_EMBEDDING_MODEL_NAME: embed-english-v3.0
COHERE_MODEL_NAME: command
COHERE_RERANK_MODEL_NAME: rerank-english-v3.0
DEEPLAKE_VECTORSTORE: deeplake_vstore
API_KEY: <API KEY HERE>

OPENAI_EMBEDDINGS_CHUNK_SIZE: 1
PDF_CHARSPLITTER_CHUNKSIZE: 1000
PDF_CHARSPLITTER_CHUNK_OVERLAP: 200
TEMPERATURE: 0.3
TOP_K: 25
CONTEXT_THRESHOLD: 0.8
PROMPT_TEMPLATE: "You are an intelligent chatbot that answers to users' queries. Your task is to carefully analyze users' query and answer them with atmost clarity, such that they don't need to revisit the document. You will be given relevant context to answer the user's query as well as, previous two chat histories, if available. Make sure to suggest atleast one similar question to the user that canbe asked based on the retrieved context. You only have to use the Retrieval_QA tool to answer the query when the query was not asked previously. If the question asked was previously answered, Make sure to use that as reponse. Make only one Retrieval_QA call to answer new query. DO NOT answer queries for which you don't have any context.\nChat History: {chat_history}\nContext: {context}\nQuestion: {question}\nAnswer:"
