HOST: localhost
PORT: 8908

MONGO_URI: <MONGO URI>

COHERE_EMBEDDING_MODEL_NAME: embed-english-v3.0
COHERE_MODEL_NAME: command
COHERE_RERANK_MODEL_NAME: rerank-english-v3.0
DEEPLAKE_VECTORSTORE: deeplake_vstore
API_KEY: <COHERE API KEY>